tenant: alexkhimich
app: sls
service: serverless-enterprise # NOTE: optionally update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.37.1"

provider:
  name: aws
  iamRoleStatements:
      - Effect: Allow
        Action:
          - ec2:RevokeSecurityGroupIngress
        Resource: "*"

plugins:
  - '@serverless/enterprise-plugin'
  - serverless-offline
  - serverless-iam-roles-per-function
functions:
  hello:
    handler: handler.hello
    runtime: nodejs8.10
    events:
      - http:
          path: hello
          method: post
  portSecurer:
    handler: port.securer
    runtime: python2.7
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.ec2
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventName:
                - AuthorizeSecurityGroupIngress
